package app;

import database.DBBarang;
import database.DBTransaksi;
import database.Database;
import java.math.BigDecimal;
import java.text.DecimalFormat;
import java.text.DecimalFormatSymbols;
import java.util.ArrayList;
import java.util.Calendar;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Nugraha
 */
public class DataPenjualan extends javax.swing.JInternalFrame {
    private DBBarang barangModel;
    private DBTransaksi transaksiModel;
    ArrayList<Integer> barangIdList = (ArrayList<Integer>) new ArrayList();
    ArrayList<BigDecimal> barangHargaList = (ArrayList<BigDecimal>) new ArrayList();
    
    private DefaultTableModel tm;
    private BigDecimal total = BigDecimal.ZERO;
    // cart[0] = id, cart[1] = quantity, cart[2] = subtotal
    ArrayList[] cart = {(ArrayList<Integer>) new ArrayList(), (ArrayList<Integer>) new ArrayList(), (ArrayList<BigDecimal>) new ArrayList()};
    
    /**
     * Creates new form DataPemilik
     */
    public DataPenjualan(int idKaryawan) {
        initComponents();
        
        barangModel = new DBBarang(Database.getConnection(), idKaryawan);
        transaksiModel = new DBTransaksi(Database.getConnection(), idKaryawan);
        
        setTable();
        getComboKategori();
        getComboBarang();
        setCurrentDateTime();
    }
    
    public void setCurrentDateTime() {
        Calendar time = Calendar.getInstance();
        dcTanggal.setDate(time.getTime());
        tfWaktu.setText(String.valueOf(time.get(Calendar.HOUR_OF_DAY)) + ":" + String.valueOf(time.get(Calendar.MINUTE)));
    }
    
    public void clear() {
        tfId.setText("");
        tfNama.setText("");
        tfNama.setText("");
        tfBiaya.setText("");
        setCurrentDateTime();
        setTable();
        total = BigDecimal.ZERO;
        updateTotal(BigDecimal.ZERO);
    }
    
    public void setTable() {
        String[] columns = {"Barang", "Jumlah", "Subtotal"};
        tm = new DefaultTableModel(null, columns) {
            @Override
            public boolean isCellEditable(int row, int column) {
                return false;
            }
        };
        dataTable.setModel(tm);
    }
    
    public String formatMoney(BigDecimal i) {
        DecimalFormatSymbols otherSymbols = new DecimalFormatSymbols();
        otherSymbols.setDecimalSeparator(',');
        otherSymbols.setGroupingSeparator('.'); 
        DecimalFormat df = new DecimalFormat("###,###.##", otherSymbols);
        df.setMaximumFractionDigits(2);
        df.setMinimumFractionDigits(2);
        return df.format(i);
    }
    
    public void getComboKategori() {
        cbKategori.removeAllItems();
        
        ArrayList<String> kategoriList = barangModel.getListKategori();
        
        for(String i : kategoriList) {
            cbKategori.addItem(i);
        }
    }
    
    public void getComboBarang() {
        cbBarang.removeAllItems();
        
        Object[] data = barangModel.getListBarang((String) cbKategori.getSelectedItem());
        
        this.barangIdList = (ArrayList<Integer>) data[0];
        this.barangHargaList = (ArrayList<BigDecimal>) data[2];
        
        for(String i : (ArrayList<String>) data[1]) {
            cbBarang.addItem(i);
        }
    }
    
    public void updateHargaBarang() {
        int jumlah;
        
        try {
            jumlah = Integer.valueOf(tfJumlah.getText());
        } catch(NumberFormatException e) {
            tfHarga.setText("???");
            return;
        }
        
        tfHarga.setText(formatMoney(barangHargaList.get(cbBarang.getSelectedIndex()).multiply(new BigDecimal(jumlah))));
    }
    
    public void updateTotal(BigDecimal newsubtotal) {
        total = total.add(newsubtotal);
        lTotal.setText(formatMoney(total.add(new BigDecimal(tfBiaya.getText()))));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSeparator2 = new javax.swing.JSeparator();
        jButton1 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        bSimpan = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        tfBiaya = new javax.swing.JTextField();
        tfNama = new javax.swing.JTextField();
        tfId = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        dcTanggal = new com.toedter.calendar.JDateChooser();
        jLabel10 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        tfWaktu = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        cbKategori = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        cbBarang = new javax.swing.JComboBox<>();
        jLabel7 = new javax.swing.JLabel();
        tfJumlah = new javax.swing.JTextField();
        bTambah = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        tfHargaSatuan = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        tfHarga = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        dataTable = new javax.swing.JTable();
        bHapus = new javax.swing.JButton();
        lTotal = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();

        jButton1.setText("jButton1");

        jLabel4.setText("jLabel4");

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("Penjualan");

        bSimpan.setText("Simpan Transaksi");
        bSimpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bSimpanActionPerformed(evt);
            }
        });

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Info Penjualan"));

        tfBiaya.setHorizontalAlignment(javax.swing.JTextField.TRAILING);
        tfBiaya.setText("0");
        tfBiaya.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tfBiayaKeyReleased(evt);
            }
        });

        tfId.setEnabled(false);

        jLabel1.setText("ID");

        jLabel3.setText("Nama Pembeli");

        jLabel5.setText("Biaya Service");

        dcTanggal.setDateFormatString("dd/MM/yyyy");

        jLabel10.setText("Tanggal");

        jLabel12.setText("Waktu");

        tfWaktu.setText("00:00");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(jLabel1)
                    .addComponent(jLabel5)
                    .addComponent(jLabel10)
                    .addComponent(jLabel12))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(dcTanggal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(tfBiaya, javax.swing.GroupLayout.DEFAULT_SIZE, 165, Short.MAX_VALUE)
                    .addComponent(tfId)
                    .addComponent(tfNama)
                    .addComponent(tfWaktu, javax.swing.GroupLayout.Alignment.TRAILING))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(tfId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(tfNama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(tfBiaya, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jLabel10))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(dcTanggal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(tfWaktu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Barang yang Dibeli"));

        jLabel2.setText("Kategori");

        cbKategori.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbKategoriActionPerformed(evt);
            }
        });

        jLabel6.setText("Barang");

        cbBarang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbBarangActionPerformed(evt);
            }
        });

        jLabel7.setText("Jumlah");

        tfJumlah.setHorizontalAlignment(javax.swing.JTextField.TRAILING);
        tfJumlah.setText("1");
        tfJumlah.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tfJumlahKeyReleased(evt);
            }
        });

        bTambah.setText("Tambah");
        bTambah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bTambahActionPerformed(evt);
            }
        });

        jLabel8.setText("Harga Satuan");

        tfHargaSatuan.setEditable(false);
        tfHargaSatuan.setHorizontalAlignment(javax.swing.JTextField.TRAILING);
        tfHargaSatuan.setText("0");

        jLabel9.setText("Harga");

        tfHarga.setEditable(false);
        tfHarga.setHorizontalAlignment(javax.swing.JTextField.TRAILING);
        tfHarga.setText("0");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel6)
                            .addComponent(jLabel8)
                            .addComponent(jLabel7)
                            .addComponent(jLabel9))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tfHarga)
                            .addComponent(cbBarang, 0, 249, Short.MAX_VALUE)
                            .addComponent(cbKategori, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(tfJumlah)
                            .addComponent(tfHargaSatuan)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(bTambah)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(cbKategori, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(cbBarang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(tfHargaSatuan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(tfJumlah, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(tfHarga, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 10, Short.MAX_VALUE)
                .addComponent(bTambah)
                .addContainerGap())
        );

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder("Daftar Barang"));

        dataTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(dataTable);

        bHapus.setText("Hapus Barang");
        bHapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bHapusActionPerformed(evt);
            }
        });

        lTotal.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        lTotal.setText("0");

        jLabel11.setText("Total:");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 682, Short.MAX_VALUE)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(bHapus)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel11)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 425, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 155, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bHapus)
                    .addComponent(lTotal)
                    .addComponent(jLabel11))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(bSimpan, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(bSimpan)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bSimpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bSimpanActionPerformed
        Object[] data = {tfId.getText(), tfNama.getText(), tfBiaya.getText(), dcTanggal.getDate(),
            tfWaktu.getText(), cart[0], cart[1], cart[2]
        };
        
        if(((String) data[0]).length() < 1) { data[0] = 0; } else { data[0] = Integer.valueOf((String) data[0]); }
        
        try {
            if(((String) data[2]).length() < 1) { data[2] = BigDecimal.ZERO; } else { data[2] = new BigDecimal((String) data[2]); }
        } catch(NumberFormatException e) {
            JOptionPane.showMessageDialog(null, "Biaya tidak valid.");
            return;
        }
        
        try {
            String[] waktu = ((String) data[4]).split(":");
            ((Date) data[3]).setHours(Integer.valueOf(waktu[0]));
            ((Date) data[3]).setMinutes(Integer.valueOf(waktu[1]));
        } catch(NumberFormatException e) {
            JOptionPane.showMessageDialog(null, "Waktu tidak valid.");
            return;
        }
        
        boolean save = transaksiModel.savePenjualan((int) data[0], (String) data[1], (BigDecimal) data[2], (Date) data[3], (ArrayList<Integer>) data[5], (ArrayList<Integer>) data[6], (ArrayList<BigDecimal>) data[7]);
        if(save) {
            clear();
            JOptionPane.showMessageDialog(this, "Data berhasil disimpan.");
        } else {
            JOptionPane.showMessageDialog(this, "Data gagal disimpan.");
        }
    }//GEN-LAST:event_bSimpanActionPerformed

    private void cbKategoriActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbKategoriActionPerformed
        if(cbKategori.getSelectedIndex() < 0) {
            return;
        }
        
        getComboBarang();
    }//GEN-LAST:event_cbKategoriActionPerformed

    private void cbBarangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbBarangActionPerformed
        if(cbBarang.getSelectedIndex() < 0) {
            return;
        }
        
        tfHargaSatuan.setText(formatMoney(barangHargaList.get(cbBarang.getSelectedIndex())));
        
        updateHargaBarang();
    }//GEN-LAST:event_cbBarangActionPerformed

    private void tfJumlahKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfJumlahKeyReleased
        updateHargaBarang();
    }//GEN-LAST:event_tfJumlahKeyReleased

    private void bTambahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bTambahActionPerformed
        try {
            int jumlah = Integer.valueOf(tfJumlah.getText());
            int idBarang = barangIdList.get(cbBarang.getSelectedIndex());
            int index = 0;
            boolean existing = false;
            
            existing = cart[0].contains(idBarang);
            
            if(existing) {
                index = cart[0].indexOf(idBarang);
                cart[1].set(index, (int) cart[1].get(index) + jumlah);
                cart[2].set(index, barangHargaList.get(cbBarang.getSelectedIndex()));
            } else {
                cart[0].add(idBarang);
                cart[1].add(jumlah);
                cart[2].add(barangHargaList.get(cbBarang.getSelectedIndex()));
                index = cart[0].indexOf(idBarang);
            }
            
            BigDecimal subtotal = barangHargaList.get(cbBarang.getSelectedIndex()).multiply(new BigDecimal(jumlah));
            updateTotal(subtotal);
            
            if(existing) {
                tm.setValueAt((int) cart[1].get(index), index, 1);
                
                subtotal = ((BigDecimal) cart[2].get(index)).multiply(new BigDecimal((int) cart[1].get(index)));
                tm.setValueAt(formatMoney(subtotal), index, 2);
            } else {
                tm.addRow(new String[] {cbKategori.getSelectedItem() + " " + cbBarang.getSelectedItem(), String.valueOf(jumlah), formatMoney(subtotal)});
            }
        } catch(NumberFormatException e) {
            return;
        }
    }//GEN-LAST:event_bTambahActionPerformed

    private void bHapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bHapusActionPerformed
        int[] selected = dataTable.getSelectedRows();
        if(selected.length > 0) {
            for(int i = selected.length - 1; i >= 0; i--) {
                BigDecimal h = ((BigDecimal) cart[2].get((int) selected[i])).multiply(new BigDecimal((int) cart[1].get((int) selected[i])));
                updateTotal(h.negate());
                
                tm.removeRow(selected[i]);
                cart[0].remove((int) selected[i]);
                cart[1].remove((int) selected[i]);
                cart[2].remove((int) selected[i]);
            }
        }
    }//GEN-LAST:event_bHapusActionPerformed

    private void tfBiayaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfBiayaKeyReleased
        updateTotal(BigDecimal.ZERO);
    }//GEN-LAST:event_tfBiayaKeyReleased

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bHapus;
    private javax.swing.JButton bSimpan;
    private javax.swing.JButton bTambah;
    private javax.swing.JComboBox<String> cbBarang;
    private javax.swing.JComboBox<String> cbKategori;
    private javax.swing.JTable dataTable;
    private com.toedter.calendar.JDateChooser dcTanggal;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JLabel lTotal;
    private javax.swing.JTextField tfBiaya;
    private javax.swing.JTextField tfHarga;
    private javax.swing.JTextField tfHargaSatuan;
    private javax.swing.JTextField tfId;
    private javax.swing.JTextField tfJumlah;
    private javax.swing.JTextField tfNama;
    private javax.swing.JTextField tfWaktu;
    // End of variables declaration//GEN-END:variables
}
